// Bundled list of major NSE stocks for instant, local typeahead (Yahoo's search
// isn't a prefix index and NSE's own list blocks server IPs). Covers NIFTY 50 +
// widely-tracked names; longer queries are augmented live via Yahoo search.
export const NSE_SYMBOLS: { symbol: string; name: string }[] = [
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "ITC", name: "ITC" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" },
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation" },
  { symbol: "NTPC", name: "NTPC" },
  { symbol: "POWERGRID", name: "Power Grid Corporation" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "DRREDDY", name: "Dr Reddy's Laboratories" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "LTIM", name: "LTIMindtree" },
  { symbol: "TRENT", name: "Trent" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company" },
  { symbol: "DMART", name: "Avenue Supermarts (DMart)" },
  { symbol: "PIDILITIND", name: "Pidilite Industries" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products" },
  { symbol: "DABUR", name: "Dabur India" },
  { symbol: "HAVELLS", name: "Havells India" },
  { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "DLF", name: "DLF" },
  { symbol: "VEDL", name: "Vedanta" },
  { symbol: "ETERNAL", name: "Eternal (Zomato)" },
  { symbol: "IRCTC", name: "Indian Railway Catering (IRCTC)" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "IOC", name: "Indian Oil Corporation" },
  { symbol: "GAIL", name: "GAIL India" },
  { symbol: "JIOFIN", name: "Jio Financial Services" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals" },
  { symbol: "NAUKRI", name: "Info Edge (Naukri)" },
  { symbol: "POLICYBZR", name: "PB Fintech (Policybazaar)" },
  { symbol: "PAYTM", name: "One 97 Communications (Paytm)" },
  { symbol: "NYKAA", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)" },
  { symbol: "VBL", name: "Varun Beverages" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "SHREECEM", name: "Shree Cement" },
  { symbol: "BOSCHLTD", name: "Bosch" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India" },
  { symbol: "MARICO", name: "Marico" },
  { symbol: "BERGEPAINT", name: "Berger Paints" },
  { symbol: "UNITDSPR", name: "United Spirits" },
  { symbol: "LUPIN", name: "Lupin" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life" },
  { symbol: "SBICARD", name: "SBI Cards & Payment Services" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management" },
  { symbol: "NMDC", name: "NMDC" },
  { symbol: "SAIL", name: "Steel Authority of India (SAIL)" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals (BHEL)" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation" },
  { symbol: "RECLTD", name: "REC" },
  { symbol: "PFC", name: "Power Finance Corporation" },
  { symbol: "INDUSTOWER", name: "Indus Towers" },
  { symbol: "IDEA", name: "Vodafone Idea" },
  { symbol: "YESBANK", name: "Yes Bank" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank" },
  { symbol: "FEDERALBNK", name: "Federal Bank" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "AUBANK", name: "AU Small Finance Bank" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland" },
  { symbol: "MRF", name: "MRF" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "MPHASIS", name: "Mphasis" },
  { symbol: "LTTS", name: "L&T Technology Services" },
  { symbol: "SONACOMS", name: "Sona BLW Precision (Sona Comstar)" },
  { symbol: "POLYCAB", name: "Polycab India" },
  { symbol: "ABB", name: "ABB India" },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions" },
  { symbol: "BHARATFORG", name: "Bharat Forge" },
  { symbol: "CUMMINSIND", name: "Cummins India" },
  { symbol: "PGHL", name: "Procter & Gamble Health" },
  { symbol: "GODREJPROP", name: "Godrej Properties" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences" },
  { symbol: "MANKIND", name: "Mankind Pharma" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute" },
];
